### ISSUE TITLE
leapp upgrade removes a lot  packages on the upgrading process (as marked on report file)

### ISSUE THREAD

**Issue by Xingeqwd** [oamg/leapp-repository#1020]
### Foreword
These days I am trying to transfrom from centos7 to almaLinux.
After such a days of processing, dozens question solved, fortunately the upgrade process ended successfully, 
But there are some problem appeared........_(These issues are also recurring when **rolling back and redo**)_</br>

### Condition detailed
But I found that many packagess in my system have been deleted. 
Glanced the leapp upgrade report log, I found that it was due to this.
```
# cat /var/log/leapp/leapp-report.txt
Risk Factor: high
Title: Transition from Docker to Podman in RHEL8
Summary: Docker has been deprecated in favour of Podman in Red Hat Enterprise Linux 8. The docker package is going to be removed during the upgrade without migration of existing containers.
Remediation: [hint] It is recommended to re-create the containers with the appropriate container images and reattach any in-use volumes using podman directly prior to the upgrade of the operating system, which should provide the same level of functionality. 
Key: b68cb32bb7c0f466ba48f97981c3ba7c27faf148
----------------------------------------
Risk Factor: high
Title: Packages not signed by Red Hat found on the system
Summary: The following packages have not been signed by Red Hat and may be removed during the upgrade process in case Red Hat-signed packages to be removed during the upgrade depend on them:
- GraphicsMagick
- SDL_image
-  
```
 (there are about hundred packages on the list)
i think, it should because the scipt detected these packages are not-signed, so the scipt delete them is some some actor

After the upgrade process is executed, there will still be dnf(yum) problems( might be caused by dependency etc.), 
Which are still unsolved (it has been rolled back to centos) [this is issue link](https://github.com/AlmaLinux/almalinux-deploy/issues/163)
We can all known that: In this case, it would be very very troublesome to reconfigure and redeploy such a number of packages,
So we can focus on this problem of auto-deleting first, this should be the first problem. the problem of yum(dnf) is not that important</br>

### Asking and analysing
As this master said on [this discussion](https://access.redhat.com/discussions/5780921), 
We can may add(customize) some actor to prevent the script to delete these packages
So that they would also auto-upgraded In subsequent actors, this should be the the easiest way i thought

### Others
ByTheWay, there are an error was reported during the initramfs stage:
"scan installed target kernel version: cannot detect any kernel RPM"
It should have nothing to do with this problem, right?

there are some related link :  [this discussion](https://access.redhat.com/discussions/5780921) and [this RedHat article](https://access.redhat.com/articles/4977891#actors)</br>

### Afterword
Really thanks to everyone for the generous help and patient reading!
I would appreciate to any any idea or help
And wish you all have a good good day and life!

**Comment by pirat89** [comment]
Hi @Xingeqwd , the list of the packages in the report is just saying that we do not know what is going to happen with such packages and could be removed. We are not removing such packages explicitly. If you have a package that has PRM dependencies that are satisfied with the new system as well, most likely such a package stays installed. However, many packages have requirements that are not satisfied by packages in the target system so they are going to be removed by dnf automatically. If vendors of those packages provide builds for the target system, enabling/setting correct repositories for the in-place upgrade (IPU) lead to the upgrade of such packages also - if the packaging of the target packages is done correctly. The guidance is provided here (the last link you shared)
:
* https://access.redhat.com/articles/4977891 

I do not have experience with so many third-party packages so I am not sure whether the guy read the article how to customize the upgrade and tried that, or not. Also, IPU 6 -> 7 has been more difficult to handle third-party stuff correctly. But the IPU we implemented in leapp-repository provides a lot of possibilities how to resolve such problems in easy way. It's highly possible that all packages will not be prepared for the automatic upgrade, so in such a case you will need to adress the problem creating custom actors on your own (or you can ask vendors of particular packages to provide the solution - update problematic rpms or deliver third-party actors to handle it.

From this point, I cannot imagine any technical solution that handle the issue on our side anyhow correctly - that's also the reason, why we explicitely handle only packages signed by RH, as we cannot guarantee what is the expectation regarding other packages (which is also different in case of upgrades+conversion from centos to alma, but that's problem that Elevate from almalinux needs to deal with as we do not know these rpms). That's why we inform people by the report like the one you shared, so they are aware of possible problems and they can check the DNF upgrade transaction during the preupgrade phases what is going to happen.

About `"scan installed target kernel version: cannot detect any kernel RPM"` - I guess it happened due to used kernel that is not native for the particular distribution, as we discussed earlier the removal of the check actor that blocked the upgrade. You can manually update the actor (`common/actors/scaninstalledtargetkernelversion`) to search the rpm name you expect to  have installed on the target system. I do not suggest to remove this actor as it provides msg that is important for other actors also - and the upgrade process - IIRC. But also I see that we should improve/fix the actor to search correctly for kernel-core & kernel-rt-core as expected - but in case you want to use the kernel-ml that is not native kernel for the target operating system, you will need to still handle this manually.

**Comment by Xingeqwd** [comment]
> Hi @Xingeqwd , the list of the packages in the report is just saying that we do not know what is going to happen with such packages and could be removed. We are not removing such packages explicitly. If you have a package that has PRM dependencies that are satisfied with the new system as well, most likely such a package stays installed. However, many packages have requirements that are not satisfied by packages in the target system so they are going to be removed by dnf automatically. If vendors of those packages provide builds for the target system, enabling/setting correct repositories for the in-place upgrade (IPU) lead to the upgrade of such packages also - if the packaging of the target packages is done correctly. The guidance is provided here (the last link you shared) :
> 
> * https://access.redhat.com/articles/4977891
> 
> I do not have experience with so many third-party packages so I am not sure whether the guy read the article how to customize the upgrade and tried that, or not. Also, IPU 6 -> 7 has been more difficult to handle third-party stuff correctly. But the IPU we implemented in leapp-repository provides a lot of possibilities how to resolve such problems in easy way. It's highly possible that all packages will not be prepared for the automatic upgrade, so in such a case you will need to adress the problem creating custom actors on your own (or you can ask vendors of particular packages to provide the solution - update problematic rpms or deliver third-party actors to handle it.
> 
> From this point, I cannot imagine any technical solution that handle the issue on our side anyhow correctly - that's also the reason, why we explicitely handle only packages signed by RH, as we cannot guarantee what is the expectation regarding other packages (which is also different in case of upgrades+conversion from centos to alma, but that's problem that Elevate from almalinux needs to deal with as we do not know these rpms). That's why we inform people by the report like the one you shared, so they are aware of possible problems and they can check the DNF upgrade transaction during the preupgrade phases what is going to happen.
> 
> About `"scan installed target kernel version: cannot detect any kernel RPM"` - I guess it happened due to used kernel that is not native for the particular distribution, as we discussed earlier the removal of the check actor that blocked the upgrade. You can manually update the actor (`common/actors/scaninstalledtargetkernelversion`) to search the rpm name you expect to have installed on the target system. I do not suggest to remove this actor as it provides msg that is important for other actors also - and the upgrade process - IIRC. But also I see that we should improve/fix the actor to search correctly for kernel-core & kernel-rt-core as expected - but in case you want to use the kernel-ml that is not native kernel for the target operating system, you will need to still handle this manually.
> 
> hopefully you find at least something helpful in this answer. I will keep it opened for now to remember to create a PR/ticket to improve the target kernel detection (@oamg/developers fyi)

Hello sir @pirat89  , and thank you a lot lot for your generous help,
But i still have a few question to asking you pls.

From your statement, I can understand that(only part)

- One of the solutions to the problem of deleting these packages is to customize the actor. 
- Remove (or list) these because they are not signed by REDHAT

So I have(want) to ask you about these:
Is it possible to avoid a few pakeges like [this method](https://access.redhat.com/articles/4977891#actors)  _to exclude rpm packages from upgrades_ provided by the REDHAT documentation?
![image](https://user-images.githubusercontent.com/46107662/215331249-4a110de7-b58a-4845-8c61-dabd4ddad9ac.png)

For example, deluge certainly has a corresponding package in the EPEL8 release version but it is always be deleted(on these servelral redoing). 
If i keep it with this method mentioned above, and upgrade it on hand, So that i can keep it, 

By the way, yes, I also believe that the error of `scan installed target kernel version: cannot detect any kernel RPM` should be related to the matter of “scaninstalledtargetkernelversion” actors deleting we discussed a few days ago
I forgot to mention it on the first floor, my fault

And on the final, thank you a lot lot again! and wish you have a good day!

**Comment by pirat89** [comment]
> Is it possible to avoid a few pakeges like [this method](https://access.redhat.com/articles/4977891#actors) to exclude rpm packages from upgrades provided by the REDHAT documentation i posted below?

It should be working. However, as mentioned, it could lead to various problems - e.g. blocked upgrade due to RPM conflicts. You need to experiment here to see how it's working, but yes, specifying the any packages in the `exclude` attribute, you forbid any DNF actions they would lead to removal/update/installation of such packages. Btw, have you tried to include EPEL9 repository for the upgrade? It could lead to the update of such EPEL packages, however you could hit additional issues again due to mixture of EPEL and target system packages.

You are welcome \o

**Comment by Xingeqwd** [comment]
Oh 

> > Is it possible to avoid a few pakeges like [this method](https://access.redhat.com/articles/4977891#actors) to exclude rpm packages from upgrades provided by the REDHAT documentation i posted below?
> 
> It should be working. However, as mentioned, it could lead to various problems - e.g. blocked upgrade due to RPM conflicts. You need to experiment here to see how it's working, but yes, specifying the any packages in the `exclude` attribute, you forbid any DNF actions they would lead to removal/update/installation of such packages. Btw, have you tried to include EPEL9 repository for the upgrade? It could lead to the update of such EPEL packages, however you could hit additional issues again due to mixture of EPEL and target system packages.
> 
> You are welcome \o

Yeah, man, you are right. I'll try it later

And by the way, I remember that I did not import epel8's repo at the time.
I must remember to do these in redo this time, I hope it will be smoother this time

haha, thanks!

**Comment by pirat89** [comment]
not sure whether elevate do it or not - it depends on multiple things, also on leapp data files, that are different in this case from ours (and we do not include EPEL in our repomap.json  due to various issues).

Btw, I've created issue #1021  to resolve the problem with the kernel detection. so I am closing this one.
