### ISSUE TITLE
Add a disk space check in pre-upgrade

### ISSUE THREAD

**Issue by lucamosca1** [oamg/leapp-repository#1279]
It's common practice to partition servers to optimize and safeguarding the system. It could happens that, using cloud providers, disks are very small to save costs. In my case root partition is large 10GB on every server. In one of them, upgrade failed since there wasn't enough space to download and install all required packages.
Maybe a pre-upgrade could check root partition to see if there are at least X GB for a standard system and provide a warning (I would avoid block the process, that choice should be up to admin.

**Comment by pirat89** [comment]
Thanks for the info. In such a case I think you have used the Elevate project from almalinux, which uses own forked of leapp-repository. I am aware that they used for a longer time an older leapp-repository version which has been missing number of fixes and features (this one included). It seems that they have updated the fork recently to version that should contain the changes - speaking about upstream version [0.19.0](https://github.com/oamg/leapp-repository/releases/tag/v0.19.0) and higher.

The original solution has been very bugy (providing misleading error messages as well) due to hacks we had to do to cover older XFS FSs without ftype (d_type) attributes. The solution had complete redesign done by this 2 PRs:
* https://github.com/oamg/leapp-repository/pull/1097
* https://github.com/oamg/leapp-repository/pull/1103

So I am considering this problem is nowadays resolved.
