### ISSUE TITLE
Possible error in spec file when managing RHEL9->10 upgrade

### ISSUE THREAD

**Issue by ikerexxe** [oamg/leapp-repository#1291]
# Description

When defining the package requirements there's a condition that takes into account [RHEL7](https://github.com/oamg/leapp-repository/blob/master/packaging/leapp-repository.spec#L182) (if condition) and [RHEL8](https://github.com/oamg/leapp-repository/blob/master/packaging/leapp-repository.spec#L191) (else condition), but since we have started working on the RHEL9->10 upgrade this might be wrong. I recommend that you review it and decide the best way forward.

At the moment, and in my [PR](https://github.com/oamg/leapp-repository/pull/1289), I am adding an additional condition to check if the system is RHEL9.

**Comment by pirat89** [comment]
Hi @ikerexxe , can you elaborate more on the possible error? I am not sure whether I understand your concerns. Do you know about some dependencies that are broken or incorrect regarding the existing code? If it is just because definitions in the beginning of the file are split into 3 branches (el7, 8, 9) and dependencies just in 7 and 8+, it's because I haven't discovered that time any difference between el8 & el9, so there is no sense to have empty (or just duplicated) block for el9 dependencies. If you have any specific concern about any deps, I will check it. It's possible I missed something. But so far I do not see anything specific when looking at it.

**Comment by ikerexxe** [comment]
I added the [following lines](https://github.com/oamg/leapp-repository/pull/1289/files#diff-aaf04798865e0da37aa3fdcf66bfafdb97df6d0bd49eaabb694138f1f3d0ada3R216-R219) to my PR, but I don't know if that's the best way forward, or we should do it in another way.

**Comment by pirat89** [comment]
I would do it in the same way.

**Comment by ikerexxe** [comment]
Ok, in that case I'll close this issue as I only wanted to raise awareness of this topic.
