### ISSUE TITLE
do we have plan to support local repo without configuring http sever? 

### ISSUE THREAD

**Issue by winndows** [oamg/leapp-repository#650]
Hello,

Just wondering why do not we support local repo (baseurl=file:///<path>)? And do we have plan to support local repo without configuring http sever? 

"When your custom repository is configured to point to a local directory (baseurl=file:///<path>), Leapp is unable to access the repository. "

**Comment by pirat89** [comment]
@winndows Hi.

> Just wondering why do not we support local repo (baseurl=file:///)?

Basically it's to prevent people from the broken upgrade. The problem is that this is not so simple to implement in the safe way. Leapp needs to ensure the directory (and the content) will be available during the whole upgrade and in every environment we use during the upgrade (from the container, from the upgrade initramfs environment, ...). For the testing (in testing environemnt), you can simply remove the *localreposinhibit* actor to see what happens when you use the local repositories.

Typical case when people want  this feature is use of ISO. But already using the ISO during the upgrade includes a lot of handling during the upgrade,
- to ensure the ISO is located on the local storage,
- that you are able to mount it
- you are able to mount it on the same expected path, so nothing is changed from the DNF POV
- the directory is available inside the *targetuserspace* container
...

> And do we have plan to support local repo without configuring http sever?

It is not our priority right now. But maybe it happens in future.

**Comment by winndows** [comment]
@priat89, Thanks a lot for the detailed info.
